# ==========================================================
# 全局基础配置
# ==========================================================
general:
  seed: 42                  # 全局随机种子（数据划分、模型初始化等）

# ==========================================================
# 路径配置
# ==========================================================
paths:
  xyz_path: "../mace_data_interval.xyz"
  best_model_path: "./models/best_model.pth"
  ckpt_save_dir: "./checkpoints"   # 每5轮保存模型独立文件夹

# ==========================================================
# 数据与数据集配置
# ==========================================================
data:
  max_frames: 100            # 最多使用的轨迹帧数，设为 null 则使用全部
  cutoff: 7.0               # 邻居搜索截断半径（Å），必须与模型r_max一致
  batch_size: 2             # 批大小
  train_ratio: 0.9          # 训练集占比，剩余为验证集

# ==========================================================
# 模型结构配置
# ==========================================================
model:
  model_type: "MSMACE"  # 切换模型类型
  # 多尺度几何参数
  r_max: 7.0
  r_short: 4.5
  width: 0.7
  # 公共基础参数
  short_num_bessel: 8
  long_num_bessel: 6
  num_polynomial_cutoff: 6
  max_ell: 2
  MLP_irreps: "32x0e"
  # 层数
  short_num_interactions: 2
  long_num_interactions: 1
  # 短程支路
  short_hidden_irreps: "32x0e+32x1o"
  short_correlation: 3
  # 长程支路
  long_hidden_irreps: "16x0e+16x1o"
  long_correlation: 1

# ==========================================================
# 训练超参数
# ==========================================================
training:
  lr: 1e-3
  num_epochs: 10
  force_weight: 100.0
  grad_clip_norm: 10.0       # 梯度裁剪最大范数，防止梯度爆炸
  save_interval: 5            # 每5轮保存一次模型
  sample_num_per_epoch: 10     # 每轮训练结束输出3帧预测误差

# ==========================================================
# 原子孤立能 E0s (单位: eV)
# 键为原子序数，值为对应孤立原子能量
# ==========================================================
atomic_energies:
  1: -0.28219109    # H
  5: -0.53525320    # B
  6: -0.77850906    # C
  7: -0.84998383    # N
  9: -0.54279591    # F